<h1> Numpy </h1>


In [2]:
import numpy as np

<h2> 1. Create array</h2>

In [4]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

##### Array khác với list : nó chỉ chứa các đối tượng cùng types. Nếu ko cùng thì nó sẽ cố gắng upcast

In [9]:
listt = [1,'alo']
array = np.array(listt)
type(array[0])    ## chuyển 1 thành string 

numpy.str_

##### Nếu muốn định rõ kiểu dữ liệu --> dùng dtype = 

In [11]:
array = np.array([1,2,3,4],dtype = 'float32')
type(array[0])

numpy.float32

##### Không giống list --> array có thể nhiều chiều

In [13]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Một số cách create array

In [15]:
zeros = np.zeros(10,dtype ='int')
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
one = np.ones(10,dtype='int')
one

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
full = np.full((3,3),7,dtype = 'int')
full

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [21]:
arange = np.arange(0,10,1)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
linspace = np.linspace(0,1,5)
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
random = np.random.random((4,4))  ## random giá trị giữa 0 và 1 
random

array([[0.46710736, 0.74400019, 0.82798298, 0.06622558],
       [0.7434104 , 0.73466971, 0.54059609, 0.87043257],
       [0.19729169, 0.87254384, 0.67484226, 0.36196612],
       [0.12239019, 0.757164  , 0.67572575, 0.99450992]])

In [25]:
random_nor = np.random.normal(0,1,(3,3))  ## random theo phân phối chuẩn 
random_nor                                ## mean = 0  std = 1


array([[-0.96563172, -1.69717311,  0.3816857 ],
       [ 0.67600502, -1.33467438, -2.63583233],
       [-1.26780985, -0.81026577, -0.62077157]])

In [27]:
random_int = np.random.randint(0,10,(3,3)) ## random số nguyên trong khoảng
random_int 

array([[9, 9, 0],
       [6, 7, 2],
       [2, 4, 4]])

In [29]:
eye = np.eye(4)  ## ma trận đường chéo
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

2. Numpy data type

<p>bool_ 

int_

intc

intp

int8

int16

int32

int64

uint8

uint16

uint32

uint64

float_

float_16

float_32

complex_

complex_64</p>

3. Numpy array attributes

In [32]:
array1 = np.random.randint(0,10,(3,4,5))
array1

array([[[1, 3, 2, 3, 8],
        [7, 5, 6, 4, 2],
        [2, 8, 3, 0, 7],
        [0, 8, 0, 0, 3]],

       [[7, 5, 4, 9, 1],
        [6, 6, 1, 3, 1],
        [3, 9, 1, 8, 4],
        [8, 7, 0, 6, 5]],

       [[8, 0, 5, 0, 1],
        [1, 2, 6, 8, 0],
        [1, 4, 2, 5, 1],
        [6, 3, 9, 8, 3]]])

In [33]:
print("Dim: ",array1.ndim)
print("Shape: ",array1.shape)
print("Size: ",array1.size)

Dim:  3
Shape:  (3, 4, 5)
Size:  60


4. Access Single Elements

##### Truy nhập vào từng phân tử

In [34]:
array1

array([[[1, 3, 2, 3, 8],
        [7, 5, 6, 4, 2],
        [2, 8, 3, 0, 7],
        [0, 8, 0, 0, 3]],

       [[7, 5, 4, 9, 1],
        [6, 6, 1, 3, 1],
        [3, 9, 1, 8, 4],
        [8, 7, 0, 6, 5]],

       [[8, 0, 5, 0, 1],
        [1, 2, 6, 8, 0],
        [1, 4, 2, 5, 1],
        [6, 3, 9, 8, 3]]])

In [35]:
array1[0]

array([[1, 3, 2, 3, 8],
       [7, 5, 6, 4, 2],
       [2, 8, 3, 0, 7],
       [0, 8, 0, 0, 3]])

In [42]:
array1[0,0,1]

3

In [43]:
array1[0,0,-1]

8

##### chúng ta có thể thay đổi từng phần tử này

In [45]:
array1[0,0,0] = 5
array1[0]

array([[5, 3, 2, 3, 8],
       [7, 5, 6, 4, 2],
       [2, 8, 3, 0, 7],
       [0, 8, 0, 0, 3]])

##### Khi chúng ta thay đổi 1 phần từ thành 1 phần có kiểu dữ liệu khác thì cần lưu ý

In [50]:
print(type(array1[0,0,0]))
array1[0,0,0] = 1.1111   ## nó tự động làm tròn 1 thay vì 1.1111
array1[0]

<class 'numpy.int32'>


array([[1, 3, 2, 3, 8],
       [7, 5, 6, 4, 2],
       [2, 8, 3, 0, 7],
       [0, 8, 0, 0, 3]])

5. Truy cập vào 1 array con


##### One-dimension

In [53]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
print("Từ 0 -> 4: ",x[:5])
print("Từ 5 -> hết: ",x[5:])
print("Từ 4 -> 7: ",x[4:8])

Từ 0 -> 4:  [0 1 2 3 4]
Từ 5 -> hết:  [5 6 7 8 9]
Từ 4 -> 7:  [4 5 6 7]


In [57]:
print("Start:0 - End:Hết - Step:2: ",x[::2])
print("Start:End - End:0 - Step:-1: ",x[::-1])

Start:0 - End:Hết - Step:2:  [0 2 4 6 8]
Start:End - End:0 - Step:-1:  [9 8 7 6 5 4 3 2 1 0]


##### Mutil Dimension


In [59]:
x2 = np.random.randint(0,10,(4,4))
x2

array([[7, 2, 6, 6],
       [1, 6, 6, 2],
       [7, 2, 7, 0],
       [9, 5, 3, 2]])

In [62]:
print("row:0->1 | col:2->3\n",x2[:2,2:4])

row:0->1 | col:2->3
 [[6 6]
 [6 2]]


In [64]:
print("row: 0->End(step=2) | col: 0->End(step = 2)\n",x2[::2,::2])

row: 0->End(step=2) | col: 0->End(step = 2)
 [[7 6]
 [7 7]]


Truy xuất Row hoặc Collumn

In [68]:
print("Cột 1\n",x2[:,0])
print("Hàng 1\n",x2[0,:])

Cột 1
 [7 1 7 9]
Hàng 1
 [7 2 6 6]


##### Lưu ý khi chúng ta thay đổi array thì nó sẽ trả về phiên bản đã thay đổi - khác với list

In [72]:
list1 = [1,2,3,4,5]
list2 = list1[:3]
list2[2] = 999
print("List 1: ",list1)
print("List 2: ",list2)

List 1:  [1, 2, 3, 4, 5]
List 2:  [1, 2, 999]


In [73]:
array1 = np.array([1,2,3,4,5])
array2 = array1[:3]
array2[2] = 999
print("Array 1: ",array1)
print("Array 2: ",array2)

Array 1:  [  1   2 999   4   5]
Array 2:  [  1   2 999]


##### Khi tạo array mới để ko còn liên quan đến mảng cũ -> dùng copy()

In [74]:
array1 = np.array([1,2,3,4,5])
array2 = array1[:3].copy()
array2[2] = 999
print("Array 1: ",array1)
print("Array 2: ",array2)

Array 1:  [1 2 3 4 5]
Array 2:  [  1   2 999]


6.Reshape Array

In [76]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
array = array.reshape((3,3))  ### điều kiện để reshape là cùng size
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
x = np.array([1,2,3])
x.shape

(3,)

In [82]:
print("Reshape 1*3: ",x.reshape((1,3)))
print("Reshape 3*1:\n",x.reshape((3,1)))

Reshape 1*3:  [[1 2 3]]
Reshape 3*1:
 [[1]
 [2]
 [3]]


##### Khi dùng reshape thì nó cũng là no-copy, tuy nhiên ko đúng trong tất cả trường hợp -> dùng phải để ý

In [87]:
b = x.reshape((1,3))
b[0,2] = 999
print("X: ",x)
print("B: ",b)  

X:  [  1   2 999]
B:  [[  1   2 999]]


##### Array.reshape và Array.T là khác nhau 

In [89]:
x = np.random.randint(1,9,(3,5))
x

array([[4, 2, 2, 3, 3],
       [1, 3, 8, 2, 2],
       [1, 2, 1, 1, 3]])

In [93]:
print("X=(3,5).reshape(5,3)\n",x.reshape((5,3)))
print("X=(3,5).T\n",x.T)   

X=(3,5).reshape(5,3)
 [[4 2 2]
 [3 3 1]
 [3 8 2]
 [2 1 2]
 [1 1 3]]
X=(3,5).T
 [[4 1 1]
 [2 3 2]
 [2 8 1]
 [3 2 1]
 [3 2 3]]


7.Array concatenation and Spliting ( Gộp và Cắt array)

##### * Concat of array(Gộp mảng)

##### Concatenate

In [101]:
x1 = np.array([1,2,3])
x2 = np.array([3,2,1])
np.concatenate([x1,x2])

array([1, 2, 3, 3, 2, 1])

In [97]:
x3 = np.array([1,1,1])
np.concatenate([x1,x2,x3])

array([1, 2, 3, 3, 2, 1, 1, 1, 1])

In [103]:
x1 = x1.reshape((1,3))
x2 = x2.reshape((1,3))

np.concatenate([x1,x2])

array([[1, 2, 3],
       [3, 2, 1]])

In [105]:
array_2 = np.random.randint(1,10,(2,3))
array_2

array([[1, 4, 9],
       [4, 3, 1]])

In [108]:
print(np.concatenate([array_2,array_2]))
print("---------------------------------")
print(np.concatenate([array_2,array_2], axis = 1))

[[1 4 9]
 [4 3 1]
 [1 4 9]
 [4 3 1]]
---------------------------------
[[1 4 9 1 4 9]
 [4 3 1 4 3 1]]


##### Vstack

In [110]:
x1 = np.array([1,2,3])
x2 = np.array([[3,2,1],[4,5,6]])
np.vstack([x1,x2])

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

In [115]:
x1 = np.array([1,2,3])
x2 = np.array([[3,2,1,2],[4,5,6,4]])
# np.vstack([x1,x2])   -->ERROR

##### Hstack

In [117]:
x1 = np.array([1,2,3])
x2 = np.array([3,2,1,2])
np.hstack([x1,x2])

array([1, 2, 3, 3, 2, 1, 2])

##### * Split array(Tách chuỗi)

##### split

In [131]:
x = np.array([1,2,3,99,99,3,2,1])
x1, x2, x3 = np.split(x,[3,5])
print(x1)
print("-------------------------------")
print(x2)
print("-------------------------------")
print(x3)

[1 2 3]
-------------------------------
[99 99]
-------------------------------
[3 2 1]


##### vsplit

In [130]:
x = np.array([[1,1,1,1,1],[2,2,2,2,2]])
x1,x2 = np.vsplit(x,[1])
print(x1)
print("---------------------------")
print(x2)

[[1 1 1 1 1]]
---------------------------
[[2 2 2 2 2]]


##### hsplit

In [133]:
x = np.array([1,2,3,99,99,3,2,1])
x1,x2 = np.hsplit(x,[3])
print(x1)
print("-------------------------")
print(x2)

[1 2 3]
-------------------------
[99 99  3  2  1]


#### Computation on Numpy ( Tính toán trên numpy array)

<p> Tại sao cần phải tính toán trên numpy --> Vì sự chậm chạp của các vòng lặp </p>

In [141]:
array = np.random.rand(100)
def compute_loop(array):
    output = np.empty(len(array))
    for i in range(len(array)):
        output[i] = 1.0/array[i]
    return output
    

In [143]:
%timeit compute_loop(array)

32.8 µs ± 4.89 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [144]:
%timeit 1.0/array

1.48 µs ± 170 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### Chức năng tính toán cơ bản (Universal Function)

##### Mục đích chính của việc sử dụng array ( vector hóa) để nhanh chóng và thay thế cho việc sử dụng vòng lặp

##### Số học (arithmetic)

In [151]:
x = np.arange(4)
print("x      = ",x )
print("x + 5  = ",x+5)
print("x - 5  = ",x-5)
print("x * 5  = ",x*5)
print("x / 1  = ",x/1)
print("x // 1 = ",x/1)
print("x % 1  = ",x%1)
print("x**2   = ",x**2)
print

x      =  [0 1 2 3]
x + 5  =  [5 6 7 8]
x - 5  =  [-5 -4 -3 -2]
x * 5  =  [ 0  5 10 15]
x / 1  =  [0. 1. 2. 3.]
x // 1 =  [0. 1. 2. 3.]
x % 1  =  [0 0 0 0]
x**2   =  [0 1 4 9]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [ ]:
"""
+  : np.add
-  : np.subtract 
*  : np.multiply 
/  : np.divide 
// : np.floor_divide 
** : np.power 
%  : np.mod 
"""

In [154]:
### Absolute value ( Giá trị tuyệt đối )
x = np.array([-1,-2,3,4])
print(abs(x))
print("----------")
print(np.abs(x))
print("-----------------")
print(np.absolute(x))

[1 2 3 4]
----------
[1 2 3 4]
-----------------
[1 2 3 4]


In [158]:
#### Trigonometric func ( hàm lượng giác )
array = np.linspace(0,np.pi*2,4)  ## 0-->2pi
array

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [163]:
print("sin(0,90,180,270): ",np.sin(array))
print("cos(0,90,180,270): ",np.cos(array))
print("tan(0,90,180,270): ",np.tan(array))



sin(0,90,180,270):  [ 0.00000000e+00  8.66025404e-01 -8.66025404e-01 -2.44929360e-16]
cos(0,90,180,270):  [ 1.  -0.5 -0.5  1. ]
tan(0,90,180,270):  [ 0.00000000e+00 -1.73205081e+00  1.73205081e+00 -2.44929360e-16]


In [165]:
x = np.array([1,0,-1])
print("arcsin(1,0,-1): ",np.arcsin(x))
print("arccos(1,0,-1): ",np.arccos(x))


arcsin(1,0,-1):  [ 1.57079633  0.         -1.57079633]
arccos(1,0,-1):  [0.         1.57079633 3.14159265]


In [166]:
### Exp and loga ( hàm mũ và logarit)

x = np.array([1,2,3,4])
print("x    = ",x)
print("e^x  = ",np.exp(x))
print("2^x  = ",np.exp2(x))
print("3^x  = ",np.power(3,x))

x    =  [1 2 3 4]
e^x  =  [ 2.71828183  7.3890561  20.08553692 54.59815003]
2^x  =  [ 2.  4.  8. 16.]
3^x  =  [ 3  9 27 81]


In [168]:
x = np.array([1,3,5,10])
print("x       = ",x)
print("ln(x)   = ",np.log(x))
print("log2(x) = ",np.log2(x))
print("log10(x) = ",np.log10(x))

x       =  [ 1  3  5 10]
ln(x)   =  [0.         1.09861229 1.60943791 2.30258509]
log2(x) =  [0.         1.5849625  2.32192809 3.32192809]
log10(x) =  [0.         0.47712125 0.69897    1.        ]


##### Specifying output ( Chỉ định đầu ra )


In [172]:
x = np.array([5,5,2,3,4,5])
y = np.empty(len(x))
print(y)
print("-------------")
np.add(x,5,out = y)
print(y)

[8.48798316e-314 2.12199580e-314 1.90979621e-313 6.36598737e-314
 8.48798316e-314 2.12199579e-314]
-------------
[10. 10.  7.  8.  9. 10.]


Aggregates ( tập hợp array theo 1 phương thức )



In [173]:
x = np.arange(1,10)
print(x,"\n----------------")
np.add.reduce(x)

[1 2 3 4 5 6 7 8 9] 
----------------


45

In [175]:
### Lưu lại các trạng thái mỗi lần + 
x = np.arange(1,10)
print(x,"\n----------------")
np.add.accumulate(x)

[1 2 3 4 5 6 7 8 9] 
----------------


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [178]:
### np.outer()

x = np.arange(1,4)

print("--------------------")
print(np.multiply.outer(x,x))



--------------------
[[1 2 3]
 [2 4 6]
 [3 6 9]]


#### Aggregations: Min, Max and everything 

##### Sum of array

In [182]:
array = np.random.randint(1,100,(1,100))
%timeit sum(array)
print("-------------------------")
%timeit np.sum(array)

1.77 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
-------------------------
3.8 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


##### Min and Max

In [186]:
print("MIN: ",np.min(array))
print("-----------------------")
print("MAX: ",np.max(array))

MIN:  2
-----------------------
MAX:  98


In [190]:
print("MIN: ",array.min())
print("-----------------------")
print("MAX: ",array.max())

MIN:  2
-----------------------
MAX:  98


##### Multidimensional aggregates (Rút gọn đa chiều)


In [191]:
M = np.random.random((3, 4))
print(M)

[[0.16261675 0.30806856 0.08267577 0.6201218 ]
 [0.98964865 0.02234914 0.34259028 0.43609746]
 [0.5870866  0.0848341  0.1916826  0.02337351]]


In [193]:
print("Max theo cột: ",M.max(axis = 0))
print("---------------------------------")
print("Max theo hàng: ",M.max(axis = 1))


Max theo cột:  [0.98964865 0.30806856 0.34259028 0.6201218 ]
---------------------------------
Max theo hàng:  [0.6201218  0.98964865 0.5870866 ]


In [200]:
""""
np.sum         Tính tổng elements
np.prod        Tính tích elements
np.mean        Tính median of elements 
np.std         Tính độ lệch chuẩn
np.var         Tính phương sai 
np.min         Min của array
np.max         Max của array
np.argmin      Địa chỉ của min
np.argmax      Địa chỉ của max 
np.median      Tính median
np.percentile  Tính mode 
np.any         Đánh giá xem có phần tử nào đúng(!=0) ko
np.all         Đánh giá xem có phần từ nào sai(=0) ko
"""