In [2]:
import numpy as np

### Question on Numpy Array 

1. How to create an empty and a full Numpy array ? 

In [4]:
empty_array = np.empty((2,2))
empty_array

array([[2.12199579e-314, 1.09919382e-311],
       [6.08688876e-321, 1.09919382e-311]])

In [7]:
full_array = np.full((2,2),99)
full_array

array([[99, 99],
       [99, 99]])

2. Create a Numpy array filled with all zeros ? 

In [9]:
zeros_array = np.zeros((2,2))
zeros_array 

array([[0., 0.],
       [0., 0.]])

3. Create Numpy array filled with all ones 


In [10]:
one_array = np.ones((2,2))
one_array

array([[1., 1.],
       [1., 1.]])

4. Check whether a Numpy array contains a specified now ? 

In [11]:
array = [1,2,3,4,5]
np.issnumeric(array)

AttributeError: module 'numpy' has no attribute 'issnumeric'